wandb_version: 1

learning_rate:
  desc: null
  value: 0.000214
epochs:
  desc: null
  value: 51
batch_size:
  desc: null
  value: 32
backbone:
  desc: null
  value: resnet18
_wandb:
  desc: null
  value:
    python_version: 3.12.5
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731612163
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 80
      3:
      - 1
      - 16
      - 23
      4: 3.12.5
      5: 0.17.7
      8:
      - 3
      - 5
      13: windows-amd64
